application: stackprinter
version: 1b
runtime: python
api_version: 1

builtins:
- datastore_admin: on

inbound_services:
- warmup

handlers:
- url: /test.*
  login: admin  
  script: gaeunit.py
- url: /favicon.ico
  static_files: app/static/images/favicon.ico
  upload: app/static/images/favicon.ico
- url: /robots.txt
  static_files: app/static/docs/robots.txt
  upload: app/static/docs/robots.txt
- url: /crossdomain.xml
  static_files: app/static/docs/crossdomain.xml
  upload: app/static/docs/crossdomain.xml
- url: /sitemap.xml
  static_files: app/static/docs/sitemap.xml
  upload: app/static/docs/sitemap.xml
- url: /javascripts
  static_dir: app/static/javascripts
- url: /stylesheets
  static_dir: app/static/stylesheets
- url: /images
  static_dir: app/static/images
- url: /docs
  static_dir: app/static/docs
- url: /deleted
  static_dir: app/static/deleted
- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py
  login: admin
- url: /_ereporter
  script: $PYTHON_LIB/google/appengine/ext/ereporter/report_generator.py
  login: admin
- url: /admin.*
  script: application.py
  login: admin 
- url: /_ah/warmup
  script: application.py
  login: admin 
- url: /.*
  script: application.py
  
