UNICORN_MESSAGE_ERROR = "..for the love it bears to fair maidens forgets its ferocity and wildness.. "
GENERIC_ERROR = "Ooooops, it works on my machine. Please try again later."
NOT_FOUND_ERROR = "Not found!"
SERVER_ERROR = "Server problem"
UNSUPPORTED_SERVICE_ERROR = "Unsupported service"
KEY_TEMPLATE_ERROR = "Attention: rename key_template.py in key.py and insert your API key"
API_ERROR_THROTTLING = "The server is too busy at the moment. Please try again later."
CODE_API_ERROR_THROTTLING = 0
API_ERROR_AUTH_TOKEN_NOT_AUTHORIZED = 4009