UNICORN_MESSAGE_ERROR = "..for the love it bears to fair maidens forgets its ferocity and wildness.. "
GENERIC_ERROR = "Ooooops!"
NOT_FOUND_ERROR = "Not found!"
SERVER_ERROR = "Server problem"
UNSUPPORTED_SERVICE_ERROR = "Unsupported service"
KEY_TEMPLATE_ERROR = "Attention: rename key_template.py in key.py and insert your API key"
