from web.template import CompiledTemplate, ForLoop


def about():
    loop = ForLoop()
    _dummy  = CompiledTemplate(lambda: None, "dummy")
    join_ = _dummy._join
    escape_ = _dummy._escape

    def __template__():
        yield '', join_('<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n')
        yield '', join_('<html>\n')
        yield '', join_('    <head>\n')
        yield '', join_('        <meta http-equiv="content-type" content="text/html; charset=UTF-8">\n')
        yield '', join_('        <meta name="description" content="StackPrinter - The Stack Exchange Printer Suite">\n')
        yield '', join_('        <meta name="keywords" content="printer friendly stackoverflow stackapps stack exchange">\n')
        yield '', join_('        <title>About - StackPrinter</title> \n')
        yield '', join_('        <link rel="stylesheet" href="/stylesheets/main.css">\n')
        yield '', join_('        <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">\n')
        yield '', join_('  </head>\n')
        yield '', join_('    <body>\n')
        yield '', join_('         <div id="main_container">\n')
        yield '', join_('              <div class="logo">                           \n')
        yield '', join_('              </div>\n')
        yield '', join_('              <div class="header links">\n')
        yield '', join_('                  <a class="nolines" href="/">Home</a>|<a class="nolines" href="/favorites">Favorites</a>|<a class="nolines" href="/topvoted">TopVoted</a>|<a class="nolines" href="/topprinted">TopPrinted</a>|<span class="header_current">About</span>\n')
        yield '', join_('              </div>\n')
        yield '', join_('              <div class="about">\n')
        yield '', join_('                  <br>\n')
        yield '', join_('                  <b>Printer-Friendly:</b><br>\n')
        yield '', join_('                  Using the <a href="http://www.stackexchange.com/sites">Stack Exchange</a> Network <a href="http://stackapps.com/questions/1/api-documentation-and-help">API</a> produces an essential printable view of a given <i>question id</i> with:<br>\n')
        yield '', join_('                  * All the answers<br> \n')
        yield '', join_('                  * All the comments<br>\n')
        yield '', join_('                  <br>\n')
        yield '', join_('                  The easiest way to use this service is with:<br>\n')
        yield '', join_('                  * <a href="http://userscripts.org/scripts/show/77298" >StackPrinter GreaseMonkey script</a><br>\n')
        yield '', join_('                  * <a href="javascript:(function(){var re = new RegExp(\'^http://(.*?)\\.com/questions/([0-9]+)/\');var group = re.exec(window.location.href);if (group!=null){var service = group[1];var questionid=group[2];window.open(\'http://www.stackprinter.com/export?format=HTML&service=\'+service+\'&question=\'+questionid)}else{alert(\'Attention: question id not found!\')}})()">Bookmarklet</a><br>\n')
        yield '', join_('                  <br>\n')
        yield '', join_('                  <b>Favorites:</b><br>\n')
        yield '', join_('                  Supported services:<br> \n')
        yield '', join_('                  1. The Stack Exchange Network<br>\n')
        yield '', join_("                  Retrieves and lets you print all the favorites users' questions<br>\n")
        yield '', join_('                  2. Delicious<br>\n')
        yield '', join_('                  Retrieves the latest 100 questions of a given Delicious username with the <i>stackoverflow</i> tag (<a href="http://meta.stackoverflow.com/questions/47162/save-question-to-delicious-greasemonkey-script">more info</a>).<br>                \n')
        yield '', join_('\n')
        yield '', join_('                  <br>\n')
        yield '', join_('                  <b>Top Voted:</b><br>\n')
        yield '', join_('                  Retrieves and lets you print the top voted questions by tags<br><br>\n')
        yield '', join_('                  <b>Top Printed:</b><br>\n')
        yield '', join_('                    Top voted questions list<br><br>\n')
        yield '', join_('                  <b>Info:</b><br>\n')
        yield '', join_('                  <a target="_new" href="/docs/changelog.txt">Changelog</a>/<a target="_new" href="/docs/todo.txt">ToDo</a><br>\n')
        yield '', join_('                  <a target="_new" href="http://stackapps.com/questions/179/stackprinter-the-stack-exchange-printer-suite">More info on Stack Apps</a><br>\n')
        yield '', join_('                  <a target="_new" href="http://github.com/systempuntoout/stackprinter"/>Source code on Github</a><br>\n')
        yield '', join_('                  <img src="/images/systempuntooutmail.jpg"/>    \n')
        yield '', join_('              </div>                                 \n')
        yield '', join_('          </div>\n')
        yield '', join_('  </body>\n')
        yield '', join_('</html>\n')
    return __template__

about = CompiledTemplate(about(), 'app/views/about.html')


def admin():
    loop = ForLoop()
    _dummy  = CompiledTemplate(lambda: None, "dummy")
    join_ = _dummy._join
    escape_ = _dummy._escape

    def __template__ (result):
        yield '', join_('<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n')
        yield '', join_('<html>\n')
        yield '', join_('    <head>\n')
        yield '', join_('        <meta http-equiv="content-type" content="text/html; charset=UTF-8">\n')
        yield '', join_('        <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">\n')
        yield '', join_('  </head>\n')
        yield '', join_('    <body>\n')
        yield '', join_('         <div>\n')
        yield '', join_('             <p> STACKPRINTER ADMIN CONSOLE</p>\n')
        yield '', join_('             <ul>\n')
        yield '', join_('                 <li><a href="/admin?action=quota">API quota </a></li>\n')
        yield '', join_('                 <li><a href="/admin?action=quotaauth">API quota auth </a></li>\n')
        yield '', join_('                 <li><a href="/admin?action=authkey">API quota auth key </a></li>\n')
        yield '', join_('                 <li><a href="/admin?action=memcachestats">Memcache stats </a></li>\n')
        yield '', join_('                 <li><a href="/admin?action=memcacheflush">Memcache flush </a></li>\n')
        yield '', join_('                 <li><a href="/admin?action=normalize">Normalize </a></li>                 \n')
        yield '', join_('                 <li><a href="/admin/authtokenrenewal">Auth Token renewal </a></li>\n')
        yield '', join_('                 <li><form action = "/admin" method="POST">  \n')
        yield '', join_('                     <input type="hidden" name="action" value="delete"/>\n')
        yield '', join_('                     question_id:<input type="text" name="question_id"/>\n')
        yield '', join_('                     service :<input type="text" name="service"/>\n')
        yield '', join_('                     <input type="submit" value="Delete printed and cached Q/A"/>\n')
        yield '', join_('                   </form>\n')
        yield '', join_('                 </li>\n')
        yield '', join_('                 <li><a href="/admin/topquestionsretriever">Top Question Retriever</a></li>\n')
        yield '', join_('             </ul>       \n')
        yield '', join_('             \n')
        yield '', join_('             <p><b>Result:</b></p>\n')
        for key in loop.setup(result.keys()):
            yield '', join_('             ', '* ', escape_(("%s - %s" % (key, result[key])), True), '<br>                        \n')
        yield '', join_('         </div>\n')
        yield '', join_('  </body>\n')
        yield '', join_('</html>\n')
    return __template__

admin = CompiledTemplate(admin(), 'app/views/admin.html')


def deleted():
    loop = ForLoop()
    _dummy  = CompiledTemplate(lambda: None, "dummy")
    join_ = _dummy._join
    escape_ = _dummy._escape

    def __template__ (result):
        yield '', join_('<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n')
        yield '', join_('<html>\n')
        yield '', join_('    <head>\n')
        yield '', join_('        <meta http-equiv="content-type" content="text/html; charset=UTF-8">\n')
        yield '', join_('        <meta name="description" content="StackPrinter - The Stack Exchange Printer Suite">\n')
        yield '', join_('        <meta name="keywords" content="printer friendly stackoverflow stackapps stack exchange">\n')
        yield '', join_('        <title>Deleted - StackPrinter</title> \n')
        yield '', join_('        <link rel="stylesheet" href="/stylesheets/search.css">\n')
        yield '', join_('        <link rel="stylesheet" href="/stylesheets/main.css">\n')
        yield '', join_('        <link rel="stylesheet" href="/stylesheets/jquery-ui.css">\n')
        yield '', join_('        <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">\n')
        yield '', join_('        <script type="text/javascript" src="/javascripts/jquery-1.4.2.min.js"></script>\n')
        yield '', join_('        <script type="text/javascript" src="/javascripts/jquery-ui.min.js"></script>\n')
        yield '', join_('        <script type="text/javascript" src="/javascripts/main.js"></script>     \n')
        yield '', join_('  </head>\n')
        yield '', join_('    <body>\n')
        yield '', join_('             <div id="back">\n')
        yield '', join_('                    <a href="/"><img title="Back to home" width="20px" height="20px" border="0" src="/images/icon_home.png"/></a>\n')
        yield '', join_('                 </div>\n')
        yield '', join_('             <div id="title" class="main"><i>Deleted</i> questions</div>\n')
        yield '', join_('             <table cellpadding="2" cellspacing="0">\n')
        yield '', join_('                    <tr class="even">\n')
        yield '', join_('                            <td class="printer">\n')
        yield '', join_('                            <a target="_blank" href="/deleted/what-is-your-solution-to-the-fizzbuzz-problem.html"/>\n')
        yield '', join_('                                <img title="Printer-Friendly" src="images/printer_black.png"/>\n')
        yield '', join_('                            </a>\n')
        yield '', join_('                        </td>\n')
        yield '', join_('                        <td class="service_logo">\n')
        yield '', join_('                            <a target="_blank" href="http://stackoverflow.com"><img src="http://sstatic.net/stackoverflow/img/apple-touch-icon.png"/></a>\n')
        yield '', join_('                        </td>\n')
        yield '', join_('                        <td class="service_name">\n')
        yield '', join_('                            [Stack Overflow]    \n')
        yield '', join_('                        </td>    \n')
        yield '', join_('                        <td class="title">\n')
        yield '', join_('                            <a target="_blank" href="http://stackoverflow.com/questions/437"/>What is your solution to the FizzBuzz problem?</a><br>\n')
        yield '', join_('                            <span class="tag">\n')
        yield '', join_('                                [ language-agnostic interview-questions code-golf rosetta-stone fizzbuzz ]  \n')
        yield '', join_('                            </span>\n')
        yield '', join_('                        </td>\n')
        yield '', join_('                        <td class="counter">\n')
        yield '', join_('                                [Static]\n')
        yield '', join_('                        </td>\n')
        yield '', join_('                    </tr>\n')
        for question in loop.setup(result):
            yield '', join_('                    ', '<tr class="', escape_(loop.parity, True), '">\n')
            yield '', join_('                    ', '    <td class="printer">\n')
            yield '', join_('                    ', '        <a target="_blank" href="/export?question=', escape_((question.question_id), True), '&format=HTML&service=', escape_((question.service), True), '&linktohome=false"/>\n')
            yield '', join_('                    ', '            <img title="Printer-Friendly" src="images/printer_black.png"/>\n')
            yield '', join_('                    ', '        </a>\n')
            yield '', join_('                    ', '    </td>\n')
            yield '', join_('                    ', '    <td class="service_logo">\n')
            yield '', join_('                    ', '        <a target="_blank" href="', escape_((supported_services.info[question.service]['site_url']), True), '"><img src="', escape_((supported_services.info[question.service]['icon_url']), True), '"/></a>\n')
            yield '', join_('                    ', '    </td>\n')
            yield '', join_('                    ', '    <td class="service_name">\n')
            yield '', join_('                    ', '        [', escape_((supported_services.info[question.service]['name']), True), ']    \n')
            yield '', join_('                    ', '    </td>    \n')
            yield '', join_('                    ', '    <td class="title">\n')
            yield '', join_('                    ', '        <a target="_blank" href="', escape_(question.get_url(), True), '"/>', escape_(htmlquote(question.title), True), '</a><br>\n')
            yield '', join_('                    ', '        <span class="tag">\n')
            yield '', join_('                    ', '            [', escape_((", ".join([tag for tag in question.tags])), True), ']\n')
            yield '', join_('                    ', '        </span>\n')
            yield '', join_('                    ', '    </td>\n')
            yield '', join_('                    ', '    <td class="counter">\n')
            yield '', join_('                    ', '            [', escape_((question.counter), True), ']\n')
            yield '', join_('                    ', '    </td>\n')
            yield '', join_('                    ', '</tr>\n')
        else:
            if len(result) == 0:
                yield '', join_('                    ', '<p id="not_found">\n')
                yield '', join_('                    ', '    No questions found\n')
                yield '', join_('                    ', '</p>\n')
        yield '', join_('  </body>\n')
        yield '', join_('</html>\n')
    return __template__

deleted = CompiledTemplate(deleted(), 'app/views/deleted.html')


def export():
    loop = ForLoop()
    _dummy  = CompiledTemplate(lambda: None, "dummy")
    join_ = _dummy._join
    escape_ = _dummy._escape

    def __template__ (service, post, pretty_links, printer, link_to_home):
        yield '', join_('<html>\n')
        yield '', join_('        <head>\n')
        yield '', join_('                <meta http-equiv="content-type" content="text/html; charset=UTF-8">\n')
        yield '', join_('                <link rel="stylesheet" href="/stylesheets/export.css">\n')
        yield '', join_('                <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">\n')
        yield '', join_('                <link rel="canonical" href="http://www.stackprinter.com/export?service=', escape_(service, True), '&question=', escape_((post.question['question_id']), True), '&printer=false&linktohome=true"/>\n')
        yield '', join_('                <title>', escape_(post.question['title'], True), '</title>\n')
        yield '', join_('                <script type="text/javascript" src="/javascripts/jquery-1.4.2.min.js"></script>\n')
        yield '', join_('                <script type="text/javascript" src="/javascripts/main.js"></script>\n')
        if service in TEX_ENABLED_SERVICES:
            yield '', join_('                ', '<script type="text/javascript" src="http://mathjax.connectmv.com/MathJax.js">\n')
            yield '', join_('                ', '        MathJax.Hub.Config({extensions: ["tex2jax.js", "TeX/AMSmath.js", "TeX/noUndefined.js", "TeX/AMSsymbols.js"],"HTML-CSS": { preferredFont: "TeX", imageFont: null, availableFonts: ["STIX","TeX"], webFont: "TeX" },jax: ["input/TeX","output/HTML-CSS"],TeX: { noUndefined: { attributes: { mathcolor: "red", mathbackground: "#FFEEEE", mathsize: "90%" } } }});MathJax.Hub.Startup.onload();\n')
            yield '', join_('                ', '</script>\n')
            if printer:
                yield '', join_('                ', '<script>\n')
                yield '', join_('                ', '    MathJax.Hub.Queue(["Delay",MathJax.Callback,700],Print)\n')
                yield '', join_('                ', '</script>\n')
        else:
            if printer:
                yield '', join_('                ', '<script>\n')
                yield '', join_('                ', '    jQuery(document).ready(function(){Print();});\n')
        yield '', join_('                </script>\n')
        yield '', join_('    </head>\n')
        yield '', join_('        <body>\n')
        yield '', join_('            <div id="home">\n')
        if link_to_home:
            yield '', join_('                ', '<a href="/"><img title="Back to home" width="20px" height="20px" border="0" src="/images/icon_home.png"/></a>\n')
        yield '', join_('                <a href="http://www.stackprinter.com/export?format=HTML&service=', escape_(service, True), '&printer=false&question=', escape_((post.question['question_id']), True), '"><img title="Link to this printed question" width="20px" height="20px" border="0" src="/images/Share.gif"/></a>\n')
        yield '', join_('            </div>\n')
        yield '', join_('            <div id="donate">\n')
        yield '', join_('                <p style="margin-bottom:3px;">App Engine <a class="link" href="http://groups.google.com/group/google-appengine/browse_frm/thread/a1b7c68db2243932/e70dab7082473730?pli=1">hosting</a> help</p>\n')
        yield '', join_('                <form action="https://www.paypal.com/cgi-bin/webscr" method="post">\n')
        yield '', join_('            <input type="hidden" name="cmd" value="_s-xclick">\n')
        yield '', join_('            <input type="hidden" name="encrypted" value="-----BEGIN PKCS7-----MIIHPwYJKoZIhvcNAQcEoIIHMDCCBywCAQExggEwMIIBLAIBADCBlDCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20CAQAwDQYJKoZIhvcNAQEBBQAEgYABstDutTNVcANU/nT7NpbMDiaPvMJUeDp2yewhFhEU+687+vIKdvxAjhgX+vOWsRg8gMv3Pm6Nqv1QjaiE3DiSMgv8b5J8AVAN+jQ4a+JIIhb7b4gEOC4jOCtUtsfl2D6f8WKm+KAcbtd//NnIvVnEvdLK7uTCopJz2fBjM0qLCjELMAkGBSsOAwIaBQAwgbwGCSqGSIb3DQEHATAUBggqhkiG9w0DBwQIlWGnM1hdRmKAgZjlTyM3ZMo1xsq9CjDDjpSkQujQ0Ktm86zPMaHwj/UfPny0P/4oI1KwZCav+vJyne9s/uwDi4bUt9WfrjFFDSHFghhUQtmZBx89nSKHW7bWA9TNdqLJjRIvv9buqSEUml/wuZLnpolZWAFPU55P0aKZWaBs2TrCkGS+AtW51n1F5P+L46GQ/cKpoBMRnNSixr2RdRXE292D76CCA4cwggODMIIC7KADAgECAgEAMA0GCSqGSIb3DQEBBQUAMIGOMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxFDASBgNVBAoTC1BheVBhbCBJbmMuMRMwEQYDVQQLFApsaXZlX2NlcnRzMREwDwYDVQQDFAhsaXZlX2FwaTEcMBoGCSqGSIb3DQEJARYNcmVAcGF5cGFsLmNvbTAeFw0wNDAyMTMxMDEzMTVaFw0zNTAyMTMxMDEzMTVaMIGOMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxFDASBgNVBAoTC1BheVBhbCBJbmMuMRMwEQYDVQQLFApsaXZlX2NlcnRzMREwDwYDVQQDFAhsaXZlX2FwaTEcMBoGCSqGSIb3DQEJARYNcmVAcGF5cGFsLmNvbTCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEAwUdO3fxEzEtcnI7ZKZL412XvZPugoni7i7D7prCe0AtaHTc97CYgm7NsAtJyxNLixmhLV8pyIEaiHXWAh8fPKW+R017+EmXrr9EaquPmsVvTywAAE1PMNOKqo2kl4Gxiz9zZqIajOm1fZGWcGS0f5JQ2kBqNbvbg2/Za+GJ/qwUCAwEAAaOB7jCB6zAdBgNVHQ4EFgQUlp98u8ZvF71ZP1LXChvsENZklGswgbsGA1UdIwSBszCBsIAUlp98u8ZvF71ZP1LXChvsENZklGuhgZSkgZEwgY4xCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEUMBIGA1UEChMLUGF5UGFsIEluYy4xEzARBgNVBAsUCmxpdmVfY2VydHMxETAPBgNVBAMUCGxpdmVfYXBpMRwwGgYJKoZIhvcNAQkBFg1yZUBwYXlwYWwuY29tggEAMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADgYEAgV86VpqAWuXvX6Oro4qJ1tYVIT5DgWpE692Ag422H7yRIr/9j/iKG4Thia/Oflx4TdL+IFJBAyPK9v6zZNZtBgPBynXb048hsP16l2vi0k5Q2JKiPDsEfBhGI+HnxLXEaUWAcVfCsQFvd2A1sxRr67ip5y2wwBelUecP3AjJ+YcxggGaMIIBlgIBATCBlDCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20CAQAwCQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTExMDkwNjE5MjgxM1owIwYJKoZIhvcNAQkEMRYEFD+tUt+yG8OxfXB2S5x5tqI7MzrfMA0GCSqGSIb3DQEBAQUABIGAUgWW0ALv5oZi7WU0FlldUradlmuon5NystLaVHqsF8ZXP4VP6YhuUcU0kkZldqwUSvQWp2ou2YgKcladJSuApj7ClwMyXOO13ThVgPXPH0nStjItaPjN8JBebKbMoT7GJJBVJfEcYM30RJn2JNxY88LYB5oXajkBySowVNoQzZA=-----END PKCS7-----\n')
        yield '', join_('            ">\n')
        yield '', join_('            <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">\n')
        yield '', join_('            <img alt="" border="0" src="https://www.paypalobjects.com/it_IT/i/scr/pixel.gif" width="1" height="1">\n')
        yield '', join_('            </form>\n')
        yield '', join_('            \n')
        yield '', join_('            </div>         \n')
        yield '', join_('        <div id="question-block">\n')
        yield '', join_('          <div id="question-title">\n')
        yield '', join_('                 <img src="', escape_((supported_services.info[service]['icon_url']), True), '"/>', escape_(htmlquote(post.question['title']), True), '<br>\n')
        yield '', join_('          </div>\n')
        yield '', join_('          <div id="question-details">\n')
        yield '', join_('                [', escape_((['','+'][(int(post.question['up_vote_count'])-int(post.question['down_vote_count']))>0]), True), escape_((int(post.question['up_vote_count'])-int(post.question['down_vote_count'])), True), '] [', escape_(post.question['answer_count'], True), ']\n')
        yield '', join_('                 ', escape_(post.question.get('owner', {'display_name':'community_owned'})['display_name'], True), ' \n')
        yield '', join_('          </div>\n')
        yield '', join_('          <div id="question-details">\n')
        yield '', join_('              [', escape_(date_from(float(post.question['creation_date'])), True), ']\n')
        yield '', join_('          </div>\n')
        yield '', join_('          <div id="question-details">\n')
        yield '', join_('          [\n')
        for tag in loop.setup(post.question['tags']):
            yield '', join_('          ', escape_(tag, True), '\n')
        yield '', join_('          ]\n')
        yield '', join_('          </div>\n')
        yield '', join_('          <div id="question-details">\n')
        yield '', join_('          [ http://', escape_((service), True), '.com/questions/', escape_((post.question['question_id']), True), ']\n')
        if post.is_deleted():
            yield '', join_('          ', '[DELETED]\n')
        yield '', join_('          </div>\n')
        if service not in TEX_ENABLED_SERVICES:
            yield '', join_('          ', '<div id="adsense">\n')
            yield '', join_('          ', '        <script type="text/javascript"><!--\n')
            yield '', join_('          ', '        google_ad_client = "pub-3296756901484166";\n')
            yield '', join_('          ', '        /* 728x90, created 9/8/11 */\n')
            yield '', join_('          ', '        google_ad_slot = "7129208720";\n')
            yield '', join_('          ', '        google_ad_width = 728;\n')
            yield '', join_('          ', '        google_ad_height = 90;\n')
            yield '', join_('          ', '        //-->\n')
            yield '', join_('          ', '        </script>\n')
            yield '', join_('          ', '        <script type="text/javascript"\n')
            yield '', join_('          ', '        src="http://pagead2.googlesyndication.com/pagead/show_ads.js">\n')
            yield '', join_('          ', '        </script>\n')
            yield '', join_('          ', '</div>\n')
        yield '', join_('          <div id="question">\n')
        if pretty_links:
            (sup_question_body,sup_question_links) = suppify_body(post.question['body'])
            yield '', join_('          ', escape_(sup_question_body, True), '\n')
            yield '', join_('          ', '<div id="question-links">\n')
            for key in loop.setup(sup_question_links.keys()):
                yield '', join_('          ', '[', escape_((key), True), '] ', escape_((sup_question_links[key]), True), '<br>\n')
            yield '', join_('          ', '</div>\n')
        else:
            yield '', join_('          ', escape_(post.question['body'], True), '\n')
        yield '', join_('          </div>\n')
        for comment in loop.setup(post.question['comments']):
            yield '', join_('                ', '<div class="comment">\n')
            if int(comment['score']) > 0:
                yield '', join_('                    ', '(', escape_(comment['score'], True), ')    \n')
            yield '', join_('                ', '    ', escape_(comment['body'], True), ' - <b> ', escape_(comment.get('owner', {'display_name':'community_owned'})['display_name'], True), '</b>                   \n')
            yield '', join_('                ', '</div>\n')
        for answer_number, answer  in loop.setup(enumerate(post.answers)):
            yield '', join_('              ', '<div class="answer-details">\n')
            yield '', join_('              ', '    [', escape_((['','+'][(int(answer['up_vote_count'])-int(answer['down_vote_count']))>0]), True), escape_((int(answer['up_vote_count'])-int(answer['down_vote_count'])), True), ']\n')
            yield '', join_('              ', '    [', escape_(date_from(float(answer['creation_date'])), True), ']     \n')
            yield '', join_('              ', '    ', escape_(answer.get('owner', {'display_name':'community_owned'})['display_name'], True), '\n')
            if bool(answer['accepted']):
                yield '', join_('                  ', '[<img  height="17px" width="17px" src="/images/blackflag.png"/>ACCEPTED]\n')
            yield '', join_('              ', '</div>\n')
            yield '', join_('              ', '<div class="answer">\n')
            if pretty_links:
                (sup_answer_body,sup_answer_links) = suppify_body(answer['body'])
                yield '', join_('                ', escape_(sup_answer_body, True), '  \n')
                for key in loop.setup(sup_answer_links.keys()):
                    yield '', join_('                ', '[', escape_((key), True), '] ', escape_((sup_answer_links[key]), True), '<br>\n')
                yield '', join_('                ', '<br>\n')
            else:
                yield '', join_('                ', escape_(answer['body'], True), '\n')
            yield '', join_('              ', '</div>\n')
            for comment in loop.setup(answer['comments']):
                yield '', join_('              ', '<div class="comment">\n')
                if int(comment['score']) > 0:
                    yield '', join_('              ', ' (', escape_(comment['score'], True), ')    \n')
                yield '', join_('              ', escape_(comment['body'], True), ' - <b> ', escape_(comment.get('owner',{'display_name':'community_owned'})['display_name'], True), '</b>     \n')
                yield '', join_('              ', '</div>\n')
            yield '', join_('              ', '<div class="answer-pagenumber">', escape_(int(answer_number+1), True), '</div>\n')
        yield '', join_('      </div>\n')
        yield '', join_('        <script type="text/javascript">\n')
        yield '', join_('            var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");\n')
        yield '', join_('            document.write(unescape("%3Cscript src=\'" + gaJsHost + "google-analytics.com/ga.js\' type=\'text/javascript\'%3E%3C/script%3E"));\n')
        yield '', join_('        </script>\n')
        yield '', join_('        <script type="text/javascript">\n')
        yield '', join_('            try {\n')
        yield '', join_('                var pageTracker = _gat._getTracker("UA-4276204-5");\n')
        yield '', join_('                pageTracker._trackPageview();\n')
        yield '', join_('            } catch(err) {}\n')
        yield '', join_('        </script>\n')
        yield '', join_('            <script src="http://static.getclicky.com/js" type="text/javascript"></script>\n')
        yield '', join_('        <script type="text/javascript">clicky.init(250663);</script>\n')
        yield '', join_('        <noscript><p><img alt="Clicky" width="1" height="1" src="http://in.getclicky.com/250663ns.gif" /></p></noscript>\n')
        yield '', join_('  </body>\n')
        yield '', join_('</html>\n')
    return __template__

export = CompiledTemplate(export(), 'app/views/export.html')


def favorites():
    loop = ForLoop()
    _dummy  = CompiledTemplate(lambda: None, "dummy")
    join_ = _dummy._join
    escape_ = _dummy._escape

    def __template__ (message = None):
        yield '', join_('<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n')
        yield '', join_('<html>\n')
        yield '', join_('    <head>\n')
        yield '', join_('        <meta http-equiv="content-type" content="text/html; charset=UTF-8">\n')
        yield '', join_('        <meta name="description" content="StackPrinter - The Stack Exchange Printer Suite">\n')
        yield '', join_('        <meta name="keywords" content="printer friendly stackoverflow stackapps stack exchange">\n')
        yield '', join_('        <title>Favorites - StackPrinter</title> \n')
        yield '', join_('        <link rel="stylesheet" href="/stylesheets/main.css">\n')
        yield '', join_('        <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">\n')
        yield '', join_('        <script type="text/javascript" src="/javascripts/jquery-1.4.2.min.js"></script>\n')
        yield '', join_('        <script type="text/javascript" src="/javascripts/jquery.cookie.js"></script>\n')
        yield '', join_('        <script type="text/javascript">\n')
        yield '', join_('        jQuery(\n')
        yield '', join_('                function()\n')
        yield '', join_('                {   \n')
        yield '', join_('                    jQuery("#check_username").fadeOut(2000);            \n')
        yield '', join_('                        if (jQuery.cookie("USERNAME") != null){\n')
        yield '', join_('                            jQuery("#input_main").val(jQuery.cookie("USERNAME"));\n')
        yield '', join_('                        }\n')
        yield '', join_('                        else{\n')
        yield '', join_('                            jQuery("#input_main").focus();\n')
        yield '', join_('                        }\n')
        yield '', join_('                        if (jQuery.cookie("SERVICE_FAVORITES") != null){\n')
        yield '', join_('                            jQuery("#service").val(jQuery.cookie("SERVICE_FAVORITES"));\n')
        yield '', join_('                        }\n')
        yield '', join_('                        jQuery("#favorites_button").click(function() {\n')
        yield '', join_('                            input = jQuery.trim(jQuery("#input_main").val())\n')
        yield '', join_('                    if ( input != "") {\n')
        yield '', join_('                            jQuery.cookie("USERNAME", input , { expires: 50 })\n')
        yield '', join_('                            jQuery.cookie("SERVICE_FAVORITES", jQuery("#service").val() , { expires: 50 })\n')
        yield '', join_('                                jQuery("#favorites_form").submit();\n')
        yield '', join_('                        }else{\n')
        yield '', join_('                                jQuery("input_main").focus();                      \n')
        yield '', join_('                                return false;                                \n')
        yield '', join_('                        }                                                    \n')
        yield '', join_('                });\n')
        yield '', join_('                });\n')
        yield '', join_('        </script>\n')
        yield '', join_('  </head>\n')
        yield '', join_('    <body>\n')
        yield '', join_('             <div id="main_container">\n')
        yield '', join_('                  <div class="logo">                           \n')
        yield '', join_('                    </div>\n')
        yield '', join_('                  <div class="header links">\n')
        yield '', join_('                      <a class="nolines" href="/">Home</a>|<span class="header_current">Favorites</span>|<a class="nolines" href="/topvoted">TopVoted</a>|<a class="nolines" href="/topprinted">TopPrinted</a>|<a class="nolines" href="/about">About</a>\n')
        yield '', join_('                  </div>\n')
        yield '', join_('                  <br>\n')
        yield '', join_('                  <form  id="favorites_form" action="/favorites" method="POST">\n')
        yield '', join_('                      <div id="input_container_favorites">\n')
        yield '', join_('                         <span class="main">Username</span>\n')
        yield '', join_('                             <div id="input_wrapper">\n')
        yield '', join_('                                 <input maxlength="60" name="username" value="" size="20" id="input_main">\n')
        yield '', join_('                             </div>\n')
        yield '', join_('                         <div>                                       \n')
        yield '', join_('                               <select id="service" name="service">\n')
        for service_key in loop.setup(supported_services.keys):
            yield '', join_('                                   ', '  <option  value="', escape_((service_key), True), '">', escape_((supported_services.info[service_key]['name']), True), '</option>\n')
        yield '', join_('                                   <option  value="delicious">Delicious</option> \n')
        yield '', join_('                              </select>\n')
        yield '', join_('                          </div>\n')
        yield '', join_('                          <div class="button">\n')
        yield '', join_('                              <input type="image" id="favorites_button" src="/images/getquestions.png" onmouseover="this.src=\'/images/getquestions_MouseOver.png\';" onmouseout="this.src=\'/images/getquestions.png\';" />\n')
        yield '', join_('                          </div>                                        \n')
        yield '', join_('                      </div>\n')
        yield '', join_('                  </form>\n')
        yield '', join_('                  <p id="check_username">\n')
        if message:
            yield '', join_('                          ', escape_(message, True), '\n')
        yield '', join_('                  </p>                              \n')
        yield '', join_('              </div>\n')
        yield '', join_('  </body>\n')
        yield '', join_('</html>\n')
    return __template__

favorites = CompiledTemplate(favorites(), 'app/views/favorites.html')


def favorites_delicious():
    loop = ForLoop()
    _dummy  = CompiledTemplate(lambda: None, "dummy")
    join_ = _dummy._join
    escape_ = _dummy._escape

    def __template__ (username, result):
        yield '', join_('<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n')
        yield '', join_('<html>\n')
        yield '', join_('    <head>\n')
        yield '', join_('        <meta http-equiv="content-type" content="text/html; charset=UTF-8">\n')
        yield '', join_('        <meta name="description" content="StackPrinter - The Stack Exchange Printer Suite">\n')
        yield '', join_('        <meta name="keywords" content="printer friendly stackoverflow stackapps stack exchange">\n')
        yield '', join_('        <title>Favorites - StackPrinter</title> \n')
        yield '', join_('        <link rel="stylesheet" href="/stylesheets/search.css">\n')
        yield '', join_('        <link rel="stylesheet" href="/stylesheets/main.css">\n')
        yield '', join_('        <link rel="stylesheet" href="/stylesheets/jquery-ui.css">\n')
        yield '', join_('        <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">\n')
        yield '', join_('        <script type="text/javascript" src="/javascripts/jquery-1.4.2.min.js"></script>\n')
        yield '', join_('        <script type="text/javascript" src="/javascripts/jquery-ui.min.js"></script>\n')
        yield '', join_('        <script type="text/javascript" src="/javascripts/main.js"></script>\n')
        yield '', join_('  </head>\n')
        yield '', join_('    <body>\n')
        yield '', join_('        <div id="back">\n')
        yield '', join_('            <a href="/favorites"><img src="/images/search.png"/></a>\n')
        yield '', join_('        </div>\n')
        yield '', join_('             <div id="title" class="main">\n')
        yield '', join_('                 <img src="/images/delicious.jpg"/>&nbsp;Delicious <i>stackoverflow</i> questions <br>\n')
        yield '', join_('            </div>\n')
        yield '', join_('            <p id="input"><a target="_new" href="http://www.delicious.com/', escape_((username), True), '/stackoverflow">', escape_((username), True), '</a></p>\n')
        yield '', join_('            \n')
        yield '', join_('            <table cellpadding="2" cellspacing="0">\n')
        for question in loop.setup(result):
            yield '', join_('            ', '<tr class="', escape_(loop.parity, True), '">\n')
            yield '', join_('            ', '    <td class="printer">\n')
            yield '', join_('            ', '        <a target="_blank" href="/export?question=', escape_((question.question_id), True), '&format=HTML&service=', escape_((question.service), True), '&linktohome=false"/>\n')
            yield '', join_('            ', '            <img title="Printer-Friendly" src="images/printer_black.png"/>\n')
            yield '', join_('            ', '        </a>\n')
            yield '', join_('            ', '    </td>\n')
            yield '', join_('            ', '    <td class="quicklook">\n')
            yield '', join_('            ', '        <a onclick="javascript:quicklook(', escape_((question.question_id), True), ",'", escape_((question.service), True), '\');return false;" href="#"/>\n')
            yield '', join_('            ', '            <img title="Quicklook" src="images/quicklook.png"/>\n')
            yield '', join_('            ', '        </a>\n')
            yield '', join_('            ', '    </td>    \n')
            yield '', join_('            ', '    <td class="title">\n')
            yield '', join_('            ', '        <a target="_blank" href="', escape_(question.url, True), '"/>', escape_(question.title, True), '</a><br>\n')
            yield '', join_('            ', '        <span class="tag">\n')
            yield '', join_('            ', '            [', escape_((", ".join([tag for tag in question.tags_list if tag!='stackoverflow'])), True), ']\n')
            yield '', join_('            ', '        </span>\n')
            yield '', join_('            ', '    </td>\n')
            yield '', join_('            ', '    <td class="date">\n')
            yield '', join_('            ', '        [', escape_((question.creation_date.strftime('%Y-%m-%d')), True), ']\n')
            yield '', join_('            ', '    </td>\n')
            yield '', join_('            ', '</tr>\n')
            if loop.last:
                yield '', join_('            ', '</table>\n')
        else:
            if len(result) == 0:
                yield '', join_('            ', '<p id="not_found">\n')
                yield '', join_('            ', '    No links found tagged <i>stackoverflow</i> \n')
                yield '', join_('            ', '</p>                            \n')
        yield '', join_('  </body>\n')
        yield '', join_('</html>\n')
    return __template__

favorites_delicious = CompiledTemplate(favorites_delicious(), 'app/views/favorites_delicious.html')


def favorites_stackexchange():
    loop = ForLoop()
    _dummy  = CompiledTemplate(lambda: None, "dummy")
    join_ = _dummy._join
    escape_ = _dummy._escape

    def __template__ (username, user_id, result, service, pagination):
        yield '', join_('<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n')
        yield '', join_('<html>\n')
        yield '', join_('    <head>\n')
        yield '', join_('        <meta http-equiv="content-type" content="text/html; charset=UTF-8">\n')
        yield '', join_('        <meta name="description" content="StackPrinter - The Stack Exchange Printer Suite">\n')
        yield '', join_('        <meta name="keywords" content="printer friendly stackoverflow stackapps stack exchange">\n')
        yield '', join_('        <title>Favorites - StackPrinter</title> \n')
        yield '', join_('        <link rel="stylesheet" href="/stylesheets/search.css">\n')
        yield '', join_('        <link rel="stylesheet" href="/stylesheets/main.css">\n')
        yield '', join_('        <link rel="stylesheet" href="/stylesheets/jquery-ui.css">\n')
        yield '', join_('        <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">\n')
        yield '', join_('        <script type="text/javascript" src="/javascripts/jquery-1.4.2.min.js"></script>\n')
        yield '', join_('        <script type="text/javascript" src="/javascripts/jquery-ui.min.js"></script>\n')
        yield '', join_('        <script type="text/javascript" src="/javascripts/main.js"></script>     \n')
        yield '', join_('  </head>\n')
        yield '', join_('    <body>\n')
        yield '', join_('        <div id="back">\n')
        yield '', join_('                <a href="/favorites"><img src="/images/search.png"/></a>\n')
        yield '', join_('            </div>\n')
        yield '', join_('             <div id="title" class="main"><img src="', escape_((supported_services.info[service]['icon_url']), True), '"/>', escape_((supported_services.info[service]['name']), True), '&nbsp;<i>favorites</i> questions <br></div>\n')
        yield '', join_('             <p id="input"><a target="_new" href="http://', escape_((service), True), '.com/users/', escape_((user_id), True), '/', escape_((username), True), '">', escape_((username), True), '</a></p>\n')
        yield '', join_('             <table cellpadding="2" cellspacing="0">\n')
        for question in loop.setup(result):
            yield '', join_('                    ', '<tr class="', escape_(loop.parity, True), '">\n')
            yield '', join_('                    ', '    <td class="printer">\n')
            yield '', join_('                    ', '        <a target="_blank" href="/export?question=', escape_((question.question_id), True), '&format=HTML&service=', escape_((question.service), True), '&linktohome=false"/>\n')
            yield '', join_('                    ', '            <img title="Printer-Friendly" src="images/printer_black.png"/>\n')
            yield '', join_('                    ', '        </a>\n')
            yield '', join_('                    ', '    </td>\n')
            yield '', join_('                    ', '    <td class="quicklook">\n')
            yield '', join_('                    ', '        <a onclick="javascript:quicklook(', escape_((question.question_id), True), ",'", escape_((question.service), True), '\');return false;" href="#"/>\n')
            yield '', join_('                    ', '            <img title="Quicklook" src="images/quicklook.png"/>\n')
            yield '', join_('                    ', '        </a>\n')
            yield '', join_('                    ', '    </td>\n')
            yield '', join_('                    ', '    <td class="counters">\n')
            yield '', join_('                    ', '        [', escape_(question.get_votes(), True), ']<br>[', escape_(question.answer_count, True), ']\n')
            yield '', join_('                    ', '    </td>    \n')
            yield '', join_('                    ', '    <td class="title">\n')
            yield '', join_('                    ', '        <a target="_blank" href="', escape_(question.url, True), '"/>', escape_(htmlquote(question.title), True), '</a><br>\n')
            yield '', join_('                    ', '        <span class="tag">\n')
            yield '', join_('                    ', '            [', escape_((", ".join([tag for tag in question.tags_list])), True), ']\n')
            yield '', join_('                    ', '        </span>\n')
            yield '', join_('                    ', '    </td>\n')
            yield '', join_('                    ', '    <td class="date">\n')
            yield '', join_('                    ', '            [', escape_((question.creation_date.strftime('%Y-%m-%d')), True), ']\n')
            yield '', join_('                    ', '    </td>\n')
            yield '', join_('                    ', '</tr>\n')
            if loop.last:
                yield '', join_('                    ', '</table>\n')
                yield '', join_('                    ', '<table id="pagination">\n')
                yield '', join_('                    ', '    <tr>\n')
                yield '', join_('                    ', '        <td class="pagination_found">Found: ', escape_(commify(pagination.total), True), '</td>\n')
                yield '', join_('                    ', '        <td class="pagination_page">\n')
                if pagination.has_previous_entries():
                    yield '', join_('                                ', '    <a href="/favorites?service=', escape_((service), True), '&userid=', escape_((user_id), True), '&page=', escape_((pagination.page-1), True), '&pagesize=', escape_((pagination.pagesize), True), '">&laquo; prev&nbsp;&nbsp;</a>\n')
                for page in loop.setup(pagination.get_pretty_pagination()):
                    if page != -1:
                        yield '', join_('                                ', '<a href="/favorites?service=', escape_((service), True), '&userid=', escape_((user_id), True), '&page=', escape_((page), True), '&pagesize=', escape_((pagination.pagesize), True), '">\n')
                        if page == pagination.page:
                            yield '', join_('                                    ', '|', escape_((page), True), '|    \n')
                        else:
                            yield '', join_('                                    ', escape_(page, True), ' \n')
                        yield '', join_('                                ', '</a>\n')
                    else:
                        yield '', join_('                                ', escape_(pagination.separator, True), '\n')
                if pagination.has_more_entries():
                    yield '', join_('                                ', '       <a href="/favorites?service=', escape_((service), True), '&userid=', escape_((user_id), True), '&page=', escape_((pagination.page+1), True), '&pagesize=', escape_((pagination.pagesize), True), '">&nbsp;&nbsp;next &raquo;</a>\n')
                yield '', join_('                    ', '        </td>\n')
                yield '', join_('                    ', '        <td class="pagination_pagesize">Pagesize: ', escape_(pagination.pagesize, True), '</td>\n')
                yield '', join_('                    ', '    </tr>\n')
                yield '', join_('                    ', '</table>\n')
        else:
            if len(result) == 0:
                yield '', join_('                    ', '<p id="not_found">\n')
                yield '', join_('                    ', '    No questions found\n')
                yield '', join_('                    ', '</p>\n')
        yield '', join_('  </body>\n')
        yield '', join_('</html>\n')
    return __template__

favorites_stackexchange = CompiledTemplate(favorites_stackexchange(), 'app/views/favorites_stackexchange.html')


def favorites_user_selection():
    loop = ForLoop()
    _dummy  = CompiledTemplate(lambda: None, "dummy")
    join_ = _dummy._join
    escape_ = _dummy._escape

    def __template__ (users, service):
        yield '', join_('<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n')
        yield '', join_('<html>\n')
        yield '', join_('    <head>\n')
        yield '', join_('        <meta http-equiv="content-type" content="text/html; charset=UTF-8">\n')
        yield '', join_('        <meta name="description" content="StackPrinter - The Stack Exchange Printer Suite">\n')
        yield '', join_('        <meta name="keywords" content="printer friendly stackoverflow stackapps stack exchange">\n')
        yield '', join_('        <title>Favorites - StackPrinter</title> \n')
        yield '', join_('        <link rel="stylesheet" href="/stylesheets/main.css">\n')
        yield '', join_('        <link rel="stylesheet" href="/stylesheets/scrollable.css">\n')
        yield '', join_('        <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">\n')
        yield '', join_('        <script type="text/javascript" src="/javascripts/jquery-1.4.2.min.js"></script>\n')
        yield '', join_('        <script type="text/javascript" src="/javascripts/jquery.tools.min.js"></script>\n')
        yield '', join_('        <script>\n')
        yield '', join_('            jQuery(function() {\n')
        yield '', join_('                jQuery(".scrollable").scrollable({ vertical: true, mousewheel: true});\n')
        yield '', join_('            });\n')
        yield '', join_('        </script>\n')
        yield '', join_('  </head>\n')
        yield '', join_('    <body>\n')
        yield '', join_('             <div id="main_container">\n')
        yield '', join_('                  <div class="logo">                           \n')
        yield '', join_('                    </div>\n')
        yield '', join_('                  <div class="header links">\n')
        yield '', join_('                      <a class="nolines" href="/">Home</a>|<span class="header_current">Favorites</span>|<a class="nolines" href="/topvoted">TopVoted</a>|<a class="nolines" href="/topprinted">TopPrinted</a>|<a class="nolines" href="/about">About</a>\n')
        yield '', join_('                  </div>\n')
        yield '', join_('                  <div id="user_selection_container">\n')
        yield '', join_('                      <div id="result"><a href="/favorites"><img style="border:0;height:15px;width:15px"src="/images/search.png"></a>&nbsp;', escape_((len(users)), True), ' users found</div>\n')
        yield '', join_('                      <div class="scrollable vertical">\n')
        yield '', join_('                        <div class="items">\n')
        for rown, user in loop.setup(enumerate(users)):
            if rown % 3 == 0 :
                yield '', join_('                            ', '<div>\n')
            yield '', join_('                            ', '<div class="item">\n')
            yield '', join_('                            ', '    <img src="http://www.gravatar.com/avatar/', escape_((user['email_hash']), True), '?s=40&d=identicon&r=PG" />    \n')
            yield '', join_('                            ', '    <table>\n')
            yield '', join_('                            ', '        <tr>\n')
            yield '', join_('                            ', '            <td>\n')
            yield '', join_('                            ', '                <a href="/favorites?username=', escape_((user['display_name']), True), '|', escape_((user['user_id']), True), '&service=', escape_((service), True), '">', escape_((user['display_name']), True), '</a>\n')
            yield '', join_('                            ', '            </td>\n')
            yield '', join_('                            ', '        </tr>\n')
            yield '', join_('                            ', '        <tr>\n')
            yield '', join_('                            ', '            <td>\n')
            yield '', join_('                            ', '                <table>\n')
            yield '', join_('                            ', '                    <tr>\n')
            yield '', join_('                            ', '                        <td style="padding-right:20px;font-weight:bold">', escape_(commify(user['reputation']), True), '</td>\n')
            if (user['badge_counts'].get('gold',0) > 0) :
                yield '', join_('                                                    ', '<td>\n')
                yield '', join_('                                                    ', '    <img style="width:6px;height:6px;margin:0px"  src="/images/badge_gold.png"/>\n')
                yield '', join_('                                                    ', '</td>\n')
                yield '', join_('                                                    ', '<td>\n')
                yield '', join_('                                                    ', '    ', escape_((user['badge_counts'].get('gold')), True), ' \n')
                yield '', join_('                                                    ', '</td>\n')
            if (user['badge_counts'].get('silver',0) > 0) :
                yield '', join_('                                                    ', '<td>\n')
                yield '', join_('                                                    ', '    <img style="width:6px;height:6px;margin:0px" src="/images/badge_silver.png"/>\n')
                yield '', join_('                                                    ', '</td>\n')
                yield '', join_('                                                    ', '<td>\n')
                yield '', join_('                                                    ', '    ', escape_((user['badge_counts'].get('silver')), True), '\n')
                yield '', join_('                                                    ', '</td>\n')
            if (user['badge_counts'].get('bronze',0) > 0) :
                yield '', join_('                                                    ', '<td>\n')
                yield '', join_('                                                    ', '    <img style="width:6px;height:6px;margin:0px" src="/images/badge_bronze.png"/>\n')
                yield '', join_('                                                    ', '</td>\n')
                yield '', join_('                                                    ', '<td>\n')
                yield '', join_('                                                    ', '    ', escape_((user['badge_counts'].get('bronze')), True), '\n')
                yield '', join_('                                                    ', '</td>\n')
            yield '', join_('                            ', '                    </tr>\n')
            yield '', join_('                            ', '                </table>\n')
            yield '', join_('                            ', '            </td>\n')
            yield '', join_('                            ', '       </tr>\n')
            yield '', join_('                            ', '    </table>\n')
            yield '', join_('                            ', '</div>\n')
            if ((rown+1) % 3 == 0 and rown!=0) or (rown == len(users)-1):
                yield '', join_('                            ', '</div>\n')
        yield '', join_('                        </div>\n')
        yield '', join_('                      </div>\n')
        if len(users) > 3:
            yield '', join_('                      ', '<div id="actions">\n')
            yield '', join_('                      ', '     <a class="prev">&laquo; prev</a>\n')
            yield '', join_('                      ', '     <a class="next">More users &raquo;</a>\n')
            yield '', join_('                      ', '</div>\n')
        yield '', join_('                    </div>\n')
        yield '', join_('              </div>\n')
        yield '', join_('  </body>\n')
        yield '', join_('</html>\n')
    return __template__

favorites_user_selection = CompiledTemplate(favorites_user_selection(), 'app/views/favorites_user_selection.html')


def index():
    loop = ForLoop()
    _dummy  = CompiledTemplate(lambda: None, "dummy")
    join_ = _dummy._join
    escape_ = _dummy._escape

    def __template__ (counter):
        yield '', join_('<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n')
        yield '', join_('<html xmlns="http://www.w3.org/1999/xhtml">\n')
        yield '', join_('    <head>\n')
        yield '', join_('        <meta name="msvalidate.01" content="B1898196AA6A9934D5A056A346AF7EAF" />\n')
        yield '', join_('        <meta name="google-site-verification" content="Gje2eDNJYqM29mwtIs3LrR-28OBbtntH1YiNHkPS9yY" />\n')
        yield '', join_('        <meta name="google-site-verification" content="m05zkgXk41nY4dXLheGpLdTiTnx-JduC2XOamAra_6Q" />\n')
        yield '', join_('        <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>\n')
        yield '', join_('        <meta name="description" content="StackPrinter - The Stack Exchange Printer Suite. StackPrinter offers a detailed Printer-friendly rendering of Stack Exchange questions, answers and comments. ">\n')
        yield '', join_('        <meta name="keywords" content="printer-friendly stackoverflow stackapps stackexchange">\n')
        yield '', join_('        <title>StackPrinter</title> \n')
        yield '', join_('        <link rel="stylesheet" href="/stylesheets/main.css"/>\n')
        yield '', join_('        <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico"/>\n')
        yield '', join_('        <script src="http://static.getclicky.com/js" type="text/javascript"></script>\n')
        yield '', join_('        <script type="text/javascript">clicky.init(250663);</script>\n')
        yield '', join_('        <noscript><p><img alt="Clicky" width="1" height="1" src="http://in.getclicky.com/250663ns.gif" /></p></noscript>\n')
        yield '', join_('        <script type="text/javascript">\n')
        yield '', join_('            var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");\n')
        yield '', join_('            document.write(unescape("%3Cscript src=\'" + gaJsHost + "google-analytics.com/ga.js\' type=\'text/javascript\'%3E%3C/script%3E"));\n')
        yield '', join_('        </script>\n')
        yield '', join_('        <script type="text/javascript">\n')
        yield '', join_('            try {\n')
        yield '', join_('                var pageTracker = _gat._getTracker("UA-4276204-5");\n')
        yield '', join_('                pageTracker._trackPageview();\n')
        yield '', join_('            } catch(err) {}\n')
        yield '', join_('        </script>\n')
        yield '', join_('        <script type="text/javascript" src="/javascripts/jquery-1.4.2.min.js"></script>\n')
        yield '', join_('        <script type="text/javascript" src="/javascripts/typewatch.js"></script>\n')
        yield '', join_('        <script type="text/javascript">\n')
        yield '', join_('        \n')
        yield '', join_('        function getQuestion(question) {\n')
        yield '', join_("                        if (jQuery.trim(question)!=''){\n")
        yield '', join_("                        jQuery('#question_title').html('&nbsp;');\n")
        yield '', join_("                        jQuery('#input_main').addClass('ac_loading');\n")
        yield '', join_("                            var service = jQuery('#service').val();\n")
        yield '', join_('                                jQuery.getJSON("/question?question="+question+"&service="+service, function(data){\n')
        yield '', join_("                             jQuery('#question_title').text(data.title);\n")
        yield '', join_("                             jQuery('#input_main').removeClass('ac_loading');\n")
        yield '', join_('                    });\n')
        yield '', join_('             }\n')
        yield '', join_('                }\n')
        yield '', join_('        jQuery(\n')
        yield '', join_('                function()\n')
        yield '', join_('                {\n')
        yield '', join_('                        jQuery("#input_main").focus();\n')
        yield '', join_('                        jQuery("#question_button").click(function() {\n')
        yield '', join_('                    if (jQuery.trim(jQuery("#input_main").val()) != "") {\n')
        yield '', join_('                                jQuery("#question_form").submit()\n')
        yield '', join_('                        }else{\n')
        yield '', join_('                                jQuery("#input_main").focus();                                                     \n')
        yield '', join_('                        }\n')
        yield '', join_('                    return false;                                                     \n')
        yield '', join_('                });\n')
        yield '', join_("                jQuery('#input_main').bind('keypress', function(e) {\n")
        yield '', join_("                    jQuery('#question_title').html('&nbsp;');\n")
        yield '', join_('                });\n')
        yield '', join_('\n')
        yield '', join_('                jQuery("#input_main").typeWatch( {wait: 500,captureLength: -1, callback:getQuestion } );\n')
        yield '', join_('                \n')
        yield '', join_("                jQuery('#service').bind({\n")
        yield '', join_('                    keypress: function() {\n')
        yield '', join_("                    getQuestion(document.getElementById('input_main').value);\n")
        yield '', join_('                    },\n')
        yield '', join_('                    change: function() {\n')
        yield '', join_("                    getQuestion(document.getElementById('input_main').value);\n")
        yield '', join_('                    }\n')
        yield '', join_('                });\n')
        yield '', join_('                \n')
        yield '', join_("                jQuery('#input_main').bind('keyup blur',function(){ \n")
        yield '', join_("                    jQuery(this).val( jQuery(this).val().replace(/[^0-9]/g,'') ); }\n")
        yield '', join_('                );\n')
        yield '', join_('\n')
        yield '', join_('                });\n')
        yield '', join_('        </script>\n')
        yield '', join_('  </head>\n')
        yield '', join_('    <body>\n')
        yield '', join_('         <div id="main_container">\n')
        yield '', join_('              <div class="logo">                           \n')
        yield '', join_('              </div>\n')
        yield '', join_('              <div class="header links">\n')
        yield '', join_('                  <span class="header_current">Home</span>|<a class="nolines" href="/favorites">Favorites</a>|<a class="nolines" href="/topvoted">TopVoted</a>|<a class="nolines" href="/topprinted">TopPrinted</a>|<a class="nolines" href="/about">About</a>\n')
        yield '', join_('              </div>\n')
        yield '', join_('              <br/>\n')
        yield '', join_('              <form id="question_form" action="/export" method="post">\n')
        yield '', join_('                  <div id="input_container_question">\n')
        yield '', join_('                     <span class="main">Question id</span>\n')
        yield '', join_('                     <div id="input_wrapper">\n')
        yield '', join_('                         <input maxlength="10" name="question" title="StackPrinter" value="" size="12" id="input_main"/>\n')
        yield '', join_('                     </div>\n')
        yield '', join_('                     <div>                                       \n')
        yield '', join_('                          <select id="service" name="service">\n')
        for service_key in loop.setup(supported_services.keys):
            yield '', join_('                              ', '<option  value="', escape_((service_key), True), '">', escape_((supported_services.info[service_key]['name']), True), '</option> \n')
        yield '', join_('                         </select>\n')
        yield '', join_('                     </div>\n')
        yield '', join_('                     <div class="button">\n')
        yield '', join_('                         <input type="image" id="question_button" src="/images/print.png" onmouseover="this.src=\'/images/print_MouseOver.png\';" onmouseout="this.src=\'/images/print.png\';" />\n')
        yield '', join_('                     </div>\n')
        yield '', join_('                  </div>\n')
        yield '', join_('              </form>\n')
        yield '', join_('              <p id="question_title">&nbsp;</p>\n')
        yield '', join_('              <div class="links">                           \n')
        yield '', join_('                <ul id="links_block">\n')
        yield '', join_('                    <li><b>Sample</b>:  <a target="_blank" href="/export?format=HTML&service=stackoverflow&question=3800707&printer=false"/>What is negative code ?</a>\n')
        yield '', join_('                    <li><a href="http://userscripts.org/scripts/show/77298" >StackPrinter GreaseMonkey script</a></li>\n')
        yield '', join_('                    <li><a href="javascript:(function(){var re = new RegExp(\'^http://(.*?)\\.com/questions/([0-9]+)/\');var group = re.exec(window.location.href);if (group!=null){var service = group[1];var questionid=group[2];window.open(\'http://www.stackprinter.com/export?format=HTML&service=\'+service+\'&question=\'+questionid)}else{alert(\'Attention: question id not found!\')}})()">StackPrinter Bookmarklet</a></li>\n')
        yield '', join_('                    <li><a href="/deleted">Deleted questions</a></li>    \n')
        yield '', join_('                    <li><a href="http://stackapps.com/questions/179/stackprinter-the-stack-exchange-printer-suite">Feedback</a>\n')
        yield '', join_('                    <li>Questions printed so far: <b>', escape_((counter), True), '</b> </li>\n')
        yield '', join_('                </ul>\n')
        yield '', join_('              </div>\n')
        yield '', join_('              <div id="appengine_logo">\n')
        yield '', join_('                  <img margin="0" border="0" src="/images/appengine.gif"/>\n')
        yield '', join_('              </div>                                 \n')
        yield '', join_('          </div>\n')
        yield '', join_('  </body>\n')
        yield '', join_('</html>\n')
    return __template__

index = CompiledTemplate(index(), 'app/views/index.html')


def oops():
    loop = ForLoop()
    _dummy  = CompiledTemplate(lambda: None, "dummy")
    join_ = _dummy._join
    escape_ = _dummy._escape

    def __template__ (message):
        yield '', join_('<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n')
        yield '', join_('<html>\n')
        yield '', join_('    <head>\n')
        yield '', join_('        <meta http-equiv="content-type" content="text/html; charset=UTF-8">\n')
        yield '', join_('        <meta name="description" content="StackPrinter - The Stack Exchange Printer Suite">\n')
        yield '', join_('        <meta name="keywords" content="printer friendly stackoverflow stackapps stack exchange">\n')
        yield '', join_('        <title>StackPrinter</title> \n')
        yield '', join_('        <link rel="stylesheet" href="/stylesheets/main.css">\n')
        yield '', join_('        <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">\n')
        yield '', join_('  </head>\n')
        yield '', join_('    <body>\n')
        yield '', join_('         <div id="home">\n')
        yield '', join_('                <a href="/"><img width="20px" heigth="20px" border="0" src="/images/icon_home.png"/></a>\n')
        yield '', join_('            </div>\n')
        yield '', join_('         <center>\n')
        yield '', join_('              <div class="oops">                         \n')
        yield '', join_('              </div>\n')
        yield '', join_('              <br>\n')
        yield '', join_('              <div id="oops_message">                           \n')
        yield '', join_('                  ', escape_(ERROR_MESSAGE, True), '<br>\n')
        yield '', join_('                  ', escape_((message), True), '\n')
        yield '', join_('             </div>                              \n')
        yield '', join_('          </center>\n')
        yield '', join_('  </body>\n')
        yield '', join_('</html>\n')
    return __template__

oops = CompiledTemplate(oops(), 'app/views/oops.html')


def quicklook():
    loop = ForLoop()
    _dummy  = CompiledTemplate(lambda: None, "dummy")
    join_ = _dummy._join
    escape_ = _dummy._escape

    def __template__ (service, question, accepted_answer):
        yield '', join_('<div id="quicklook_question-block">\n')
        yield '', join_('  <div id="quicklook_printer">\n')
        yield '', join_('        <a target="_blank" href="/export?question=', escape_((question['question_id']), True), '&format=HTML&service=', escape_((service), True), '&linktohome=false">\n')
        yield '', join_('            <img title="Printer-Friendly" src="images/printer_black.png"/>\n')
        yield '', join_('        </a>                            \n')
        yield '', join_('  </div>\n')
        yield '', join_('  <div id="quicklook_question-title">\n')
        yield '', join_('         <img src="', escape_((supported_services.info[service]['icon_url']), True), '"/>', escape_(htmlquote(question['title']), True), '<br>\n')
        yield '', join_('  </div>\n')
        yield '', join_('  <div id="quicklook_question-details">\n')
        yield '', join_('        [', escape_((['','+'][(int(question['up_vote_count'])-int(question['down_vote_count']))>0]), True), escape_((int(question['up_vote_count'])-int(question['down_vote_count'])), True), '] [', escape_(question['answer_count'], True), ' answers]\n')
        yield '', join_('        ', escape_(question.get('owner', {'display_name':'community_owned'})['display_name'], True), '\n')
        yield '', join_('  </div>\n')
        yield '', join_('  <div id="quicklook_question-details">\n')
        yield '', join_('      [', escape_(date_from(float(question['creation_date'])), True), ']\n')
        yield '', join_('  </div>\n')
        yield '', join_('  <div id="quicklook_question-details">\n')
        yield '', join_('  [\n')
        for tag in loop.setup(question['tags']):
            yield '', join_('  ', escape_(tag, True), '\n')
        yield '', join_('  ]\n')
        yield '', join_('  </div>\n')
        yield '', join_('  <div id="quicklook_question">\n')
        yield '', join_('      ', escape_(question['body'], True), '\n')
        yield '', join_('  </div>\n')
        if accepted_answer is not None:
            yield '', join_('  ', '  <hr>\n')
            yield '', join_('  ', '  <div id="accepted_answer_block">\n')
            yield '', join_('  ', '      <div id="quicklook_answer-details">\n')
            yield '', join_('  ', '            [', escape_((['','+'][(int(accepted_answer['up_vote_count'])-int(accepted_answer['down_vote_count']))>0]), True), escape_((int(accepted_answer['up_vote_count'])-int(accepted_answer['down_vote_count'])), True), ']\n')
            yield '', join_('  ', '            [', escape_(date_from(float(accepted_answer['creation_date'])), True), ']     \n')
            yield '', join_('  ', '            ', escape_(accepted_answer.get('owner', {'display_name':'community_owned'})['display_name'], True), ' [<img  height="17px" width="17px" src="/images/blackflag.png"/>ACCEPTED]\n')
            yield '', join_('  ', '      </div>\n')
            yield '', join_('  ', '      <div id="quicklook_answer">\n')
            yield '', join_('  ', '              ', escape_(accepted_answer['body'], True), '\n')
            yield '', join_('  ', '      </div>\n')
            yield '', join_('  ', '  </div>  \n')
        yield '', join_('</div>\n')
    return __template__

quicklook = CompiledTemplate(quicklook(), 'app/views/quicklook.html')


def sitemap_index():
    loop = ForLoop()
    _dummy  = CompiledTemplate(lambda: None, "dummy")
    join_ = _dummy._join
    escape_ = _dummy._escape

    def __template__ (sitemaps):
        yield '', join_('<?xml version="1.0" encoding="UTF-8"?>\n')
        yield '', join_('<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n')
        for sitemap in loop.setup(sitemaps):
            yield '', join_('  ', '<sitemap>\n')
            yield '', join_('  ', '    <loc>http://www.stackprinter.com/sitemap_', escape_((sitemap.key().id()), True), '.xml</loc>\n')
            yield '', join_('  ', '    <lastmod>', escape_((sitemap.last_modified.strftime("%Y-%m-%d")), True), '</lastmod>\n')
            yield '', join_('  ', '</sitemap>\n')
        yield '', join_('</sitemapindex>\n')
    return __template__

sitemap_index = CompiledTemplate(sitemap_index(), 'app/views/sitemap_index.xml')


def sitemap_questions():
    loop = ForLoop()
    _dummy  = CompiledTemplate(lambda: None, "dummy")
    join_ = _dummy._join
    escape_ = _dummy._escape

    def __template__ (questions):
        yield '', join_('<?xml version="1.0" encoding="UTF-8"?>\n')
        yield '', join_('<urlset\n')
        yield '', join_('      xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n')
        yield '', join_('      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n')
        yield '', join_('      xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9\n')
        yield '', join_('http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">\n')
        for question in loop.setup(questions):
            yield '', join_('  ', '<url>\n')
            yield '', join_('  ', '  <loc>http://www.stackprinter.com/export?service=', escape_((question.split('_')[1]), True), '&amp;question=', escape_((question.split('_')[0]), True), '&amp;printer=false&amp;linktohome=true</loc>\n')
            yield '', join_('  ', '</url>\n')
        yield '', join_('</urlset>\n')
    return __template__

sitemap_questions = CompiledTemplate(sitemap_questions(), 'app/views/sitemap_questions.xml')


def topprinted():
    loop = ForLoop()
    _dummy  = CompiledTemplate(lambda: None, "dummy")
    join_ = _dummy._join
    escape_ = _dummy._escape

    def __template__ (result, page , pagesize, count):
        yield '', join_('<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n')
        yield '', join_('<html>\n')
        yield '', join_('    <head>\n')
        yield '', join_('        <meta http-equiv="content-type" content="text/html; charset=UTF-8">\n')
        yield '', join_('        <meta name="description" content="StackPrinter - The Stack Exchange Printer Suite">\n')
        yield '', join_('        <meta name="keywords" content="printer friendly stackoverflow stackapps stack exchange">\n')
        yield '', join_('        <title>Top Printed - StackPrinter</title> \n')
        yield '', join_('        <link rel="stylesheet" href="/stylesheets/search.css">\n')
        yield '', join_('        <link rel="stylesheet" href="/stylesheets/main.css">\n')
        yield '', join_('        <link rel="stylesheet" href="/stylesheets/jquery-ui.css">\n')
        yield '', join_('        <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">\n')
        yield '', join_('        <script type="text/javascript" src="/javascripts/jquery-1.4.2.min.js"></script>\n')
        yield '', join_('        <script type="text/javascript" src="/javascripts/jquery-ui.min.js"></script>\n')
        yield '', join_('        <script type="text/javascript" src="/javascripts/main.js"></script>     \n')
        yield '', join_('  </head>\n')
        yield '', join_('    <body>\n')
        yield '', join_('             <div id="back">\n')
        yield '', join_('                    <a href="/"><img title="Back to home" width="20px" height="20px" border="0" src="/images/icon_home.png"/></a>\n')
        yield '', join_('                 </div>\n')
        yield '', join_('             <div id="title" class="main"><i>Top Printed</i> questions</div>\n')
        yield '', join_('             <table cellpadding="2" cellspacing="0">\n')
        for question in loop.setup(result):
            yield '', join_('                    ', '<tr class="', escape_(loop.parity, True), '">\n')
            yield '', join_('                    ', '    <td class="printer">\n')
            yield '', join_('                    ', '        <a target="_blank" href="/export?question=', escape_((question.question_id), True), '&format=HTML&service=', escape_((question.service), True), '&linktohome=false"/>\n')
            yield '', join_('                    ', '            <img title="Printer-Friendly" src="images/printer_black.png"/>\n')
            yield '', join_('                    ', '        </a>\n')
            yield '', join_('                    ', '    </td>\n')
            yield '', join_('                    ', '    <td class="quicklook">\n')
            if question.deleted:
                yield '', join_('                            ', '<img title="Deleted" src="images/deleted.png"/>\n')
            else:
                yield '', join_('                            ', '<a onclick="javascript:quicklook(', escape_((question.question_id), True), ",'", escape_((question.service), True), '\');return false;" href="#"/>\n')
                yield '', join_('                            ', '    <img title="Quicklook" src="images/quicklook.png"/>\n')
                yield '', join_('                            ', '</a>\n')
            yield '', join_('                    ', '    </td>\n')
            yield '', join_('                    ', '    <td class="service_logo">\n')
            yield '', join_('                    ', '        <a target="_blank" href="', escape_((supported_services.info[question.service]['site_url']), True), '"><img src="', escape_((supported_services.info[question.service]['icon_url']), True), '"/></a>\n')
            yield '', join_('                    ', '    </td>\n')
            yield '', join_('                    ', '    <td class="service_name">\n')
            yield '', join_('                    ', '        [', escape_((supported_services.info[question.service]['name']), True), ']    \n')
            yield '', join_('                    ', '    </td>    \n')
            yield '', join_('                    ', '    <td class="title">\n')
            yield '', join_('                    ', '        <a target="_blank" href="', escape_(question.get_url(), True), '"/>', escape_(htmlquote(question.title), True), '</a><br>\n')
            yield '', join_('                    ', '        <span class="tag">\n')
            yield '', join_('                    ', '            [', escape_((", ".join([tag for tag in question.tags])), True), ']\n')
            yield '', join_('                    ', '        </span>\n')
            yield '', join_('                    ', '    </td>\n')
            yield '', join_('                    ', '    <td class="counter">\n')
            yield '', join_('                    ', '            [', escape_((question.counter), True), ']\n')
            yield '', join_('                    ', '    </td>\n')
            yield '', join_('                    ', '</tr>\n')
            if loop.last:
                yield '', join_('                    ', '</table>\n')
                yield '', join_('                    ', '<table id="pagination">\n')
                yield '', join_('                    ', '    <tr>\n')
                yield '', join_('                    ', '        <td class="pagination_found">Found: ', escape_(commify(count), True), '</td>\n')
                yield '', join_('                    ', '        <td class="pagination_page">\n')
                if page > 1:
                    yield '', join_('                                ', '    <a href="/topprinted?page=', escape_((page-1), True), '">&laquo; prev&nbsp;&nbsp;</a>\n')
                    yield '', join_('                                ', '\n')
                if len(result) >= pagesize:
                    yield '', join_('                                ', '       <a href="/topprinted?page=', escape_((page+1), True), '">&nbsp;&nbsp;next &raquo;</a>\n')
                yield '', join_('                    ', '        </td>\n')
                yield '', join_('                    ', '        <td class="pagination_pagesize">Pagesize: ', escape_(pagesize, True), '</td>\n')
                yield '', join_('                    ', '    </tr>\n')
                yield '', join_('                    ', '</table>\n')
        else:
            if len(result) == 0:
                yield '', join_('                    ', '<p id="not_found">\n')
                yield '', join_('                    ', '    No questions found\n')
                yield '', join_('                    ', '</p>\n')
        yield '', join_('  </body>\n')
        yield '', join_('</html>\n')
    return __template__

topprinted = CompiledTemplate(topprinted(), 'app/views/topprinted.html')


def topvoted():
    loop = ForLoop()
    _dummy  = CompiledTemplate(lambda: None, "dummy")
    join_ = _dummy._join
    escape_ = _dummy._escape

    def __template__():
        yield '', join_('<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n')
        yield '', join_('<html>\n')
        yield '', join_('    <head>\n')
        yield '', join_('        <meta http-equiv="content-type" content="text/html; charset=UTF-8">\n')
        yield '', join_('        <meta name="description" content="StackPrinter - The Stack Exchange Printer Suite">\n')
        yield '', join_('        <meta name="keywords" content="printer friendly stackoverflow stackapps stack exchange">\n')
        yield '', join_('        <title>Top Voted - StackPrinter</title> \n')
        yield '', join_('        <link rel="stylesheet" href="/stylesheets/main.css">\n')
        yield '', join_('        <link rel="stylesheet" href="/stylesheets/jquery.autocomplete.css">\n')
        yield '', join_('        <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">\n')
        yield '', join_('        <script type="text/javascript" src="/javascripts/jquery-1.4.2.min.js"></script>\n')
        yield '', join_('        <script type="text/javascript" src="/javascripts/jquery.cookie.js"></script>\n')
        yield '', join_('        <script type="text/javascript" src="/javascripts/jquery.autocomplete.min.js"></script>\n')
        yield '', join_('        <script type="text/javascript">\n')
        yield '', join_('        jQuery(\n')
        yield '', join_('                function()\n')
        yield '', join_('                {   \n')
        yield '', join_('                    jQuery("#input_main").autocomplete(\'tags\', {\n')
        yield '', join_('                                multiple: true,\n')
        yield '', join_('                                matchContains: true,\n')
        yield '', join_("                                multipleSeparator:' ',\n")
        yield '', join_('                                extraParams: { service: jQuery("#service").val()}\n')
        yield '', join_('                        });\n')
        yield '', join_('                                \n')
        yield '', join_('                        jQuery("#input_main").focus();\n')
        yield '', join_('                        \n')
        yield '', join_("                jQuery('#input_main').bind('keyup blur',function(){ \n")
        yield '', join_('                    jQuery("#input_main").setOptions({\n')
        yield '', join_('                      extraParams: { service: jQuery("#service").val() }\n')
        yield '', join_('                    }).flushCache();  \n')
        yield '', join_('                  }\n')
        yield '', join_('                );\n')
        yield '', join_('                        \n')
        yield '', join_('                        if (jQuery.cookie("SERVICE_TOPVOTED") != null){\n')
        yield '', join_('                            jQuery("#service").val(jQuery.cookie("SERVICE_TOPVOTED"));\n')
        yield '', join_('                        }\n')
        yield '', join_('                        jQuery("#topvoted_button").click(function() {\n')
        yield '', join_('                            input = jQuery.trim(jQuery("#input_main").val())\n')
        yield '', join_('                    jQuery.cookie("SERVICE_TOPVOTED", jQuery("#service").val() , { expires: 50 })\n')
        yield '', join_('                        jQuery("#topvoted_form").submit();                                                \n')
        yield '', join_('                });\n')
        yield '', join_('                });\n')
        yield '', join_('        </script>\n')
        yield '', join_('  </head>\n')
        yield '', join_('    <body>\n')
        yield '', join_('     <div id="main_container">\n')
        yield '', join_('          <div class="logo">                           \n')
        yield '', join_('            </div>\n')
        yield '', join_('          <div class="header links">\n')
        yield '', join_('              <a class="nolines" href="/">Home</a>|<a class="nolines" href="/favorites">Favorites</a>|<span class="header_current"><Favorites>TopVoted</span>|<a class="nolines" href="/topprinted">TopPrinted</a>|<a class="nolines" href="/about">About</a>\n')
        yield '', join_('          </div>\n')
        yield '', join_('          <br>\n')
        yield '', join_('          <form  id="topvoted_form" action="/topvoted" method="POST">\n')
        yield '', join_('              <div id="input_container_topvoted">\n')
        yield '', join_('                 <span class="main">Tags</span>\n')
        yield '', join_('                     <div id="input_wrapper">\n')
        yield '', join_('                         <input maxlength="60" name="tagged" value="" style="text-align:left" size="40" id="input_main">\n')
        yield '', join_('                     </div>\n')
        yield '', join_('                 <div>                                       \n')
        yield '', join_('                       <select id="service" name="service">\n')
        for service_key in loop.setup(supported_services.keys):
            yield '', join_('                           ', '  <option  value="', escape_((service_key), True), '">', escape_((supported_services.info[service_key]['name']), True), '</option>\n')
        yield '', join_('                      </select>\n')
        yield '', join_('                  </div>\n')
        yield '', join_('                  <div class="button">\n')
        yield '', join_('                      <input type="image" id="topvoted_button" src="/images/getquestions.png" onmouseover="this.src=\'/images/getquestions_MouseOver.png\';" onmouseout="this.src=\'/images/getquestions.png\';" />\n')
        yield '', join_('                  </div>\n')
        yield '', join_('              </div>\n')
        yield '', join_('          </form>                          \n')
        yield '', join_('      </div>\n')
        yield '', join_('  </body>\n')
        yield '', join_('</html>\n')
    return __template__

topvoted = CompiledTemplate(topvoted(), 'app/views/topvoted.html')


def topvoted_tagged():
    loop = ForLoop()
    _dummy  = CompiledTemplate(lambda: None, "dummy")
    join_ = _dummy._join
    escape_ = _dummy._escape

    def __template__ (tagged, result, service, pagination):
        yield '', join_('<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n')
        yield '', join_('<html>\n')
        yield '', join_('    <head>\n')
        yield '', join_('        <meta http-equiv="content-type" content="text/html; charset=UTF-8">\n')
        yield '', join_('        <meta name="description" content="StackPrinter - The Stack Exchange Printer Suite">\n')
        yield '', join_('        <meta name="keywords" content="printer friendly stackoverflow stackapps stack exchange">\n')
        yield '', join_('        <title>Top Voted - StackPrinter</title> \n')
        yield '', join_('        <link rel="stylesheet" href="/stylesheets/search.css">\n')
        yield '', join_('        <link rel="stylesheet" href="/stylesheets/main.css">\n')
        yield '', join_('        <link rel="stylesheet" href="/stylesheets/jquery-ui.css">\n')
        yield '', join_('        <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">\n')
        yield '', join_('        <script type="text/javascript" src="/javascripts/jquery-1.4.2.min.js"></script>\n')
        yield '', join_('        <script type="text/javascript" src="/javascripts/jquery-ui.min.js"></script>\n')
        yield '', join_('        <script type="text/javascript" src="/javascripts/main.js"></script>\n')
        yield '', join_('  </head>\n')
        yield '', join_('    <body>\n')
        yield '', join_('        <div id="back">\n')
        yield '', join_('                <a href="/topvoted"><img src="/images/search.png"/></a>\n')
        yield '', join_('            </div>\n')
        yield '', join_('             <div id="title" class="main"><img src="', escape_((supported_services.info[service]['icon_url']), True), '"/>', escape_((supported_services.info[service]['name']), True), '&nbsp;<i>Top Voted</i> questions </div>\n')
        yield '', join_('             <p id="input">', escape_((tagged), True), '</p>\n')
        yield '', join_('             \n')
        yield '', join_('             <table cellpadding="2" cellspacing="0">\n')
        for question in loop.setup(result):
            yield '', join_('                    ', '<tr class="', escape_(loop.parity, True), '">\n')
            yield '', join_('                    ', '    <td class="printer">\n')
            yield '', join_('                    ', '        <a target="_blank" href="/export?question=', escape_((question.question_id), True), '&format=HTML&service=', escape_((question.service), True), '&linktohome=false"/>\n')
            yield '', join_('                    ', '            <img title="Printer-Friendly" src="images/printer_black.png"/>\n')
            yield '', join_('                    ', '        </a>                            \n')
            yield '', join_('                    ', '    </td>\n')
            yield '', join_('                    ', '    <td class="quicklook">\n')
            yield '', join_('                    ', '        <a onclick="javascript:quicklook(', escape_((question.question_id), True), ",'", escape_((question.service), True), '\');return false;" href="#"/>\n')
            yield '', join_('                    ', '            <img title="Quicklook" src="images/quicklook.png"/>\n')
            yield '', join_('                    ', '        </a>\n')
            yield '', join_('                    ', '    </td>\n')
            yield '', join_('                    ', '    <td class="counters">\n')
            yield '', join_('                    ', '        [', escape_(question.get_votes(), True), ']<br>[', escape_(question.answer_count, True), ']\n')
            yield '', join_('                    ', '    </td>    \n')
            yield '', join_('                    ', '    <td class="title">\n')
            yield '', join_('                    ', '        <a target="_blank" href="', escape_(question.url, True), '"/>', escape_(htmlquote(question.title), True), '</a><br>\n')
            yield '', join_('                    ', '        <span class="tag">\n')
            yield '', join_('                    ', '            [', escape_((", ".join([tag for tag in question.tags_list])), True), ']\n')
            yield '', join_('                    ', '        </span>\n')
            yield '', join_('                    ', '    </td>\n')
            yield '', join_('                    ', '    <td class="date">\n')
            yield '', join_('                    ', '            [', escape_((question.creation_date.strftime('%Y-%m-%d')), True), ']\n')
            yield '', join_('                    ', '    </td>\n')
            yield '', join_('                    ', '</tr>\n')
            if loop.last:
                yield '', join_('                    ', '</table>\n')
                yield '', join_('                    ', '<table id="pagination">\n')
                yield '', join_('                    ', '    <tr>\n')
                yield '', join_('                    ', '        <td class="pagination_found">Found: ', escape_(commify(pagination.total), True), '</td>\n')
                yield '', join_('                    ', '        <td class="pagination_page">\n')
                if pagination.has_previous_entries():
                    yield '', join_('                                ', '    <a href="/topvoted?service=', escape_((service), True), '&tagged=', escape_((urlquote(tagged)), True), '&page=', escape_((pagination.page-1), True), '&pagesize=', escape_((pagination.pagesize), True), '">&laquo; prev&nbsp;&nbsp;</a>\n')
                for page in loop.setup(pagination.get_pretty_pagination()):
                    if page != -1:
                        yield '', join_('                                ', '<a href="/topvoted?service=', escape_((service), True), '&tagged=', escape_((urlquote(tagged)), True), '&page=', escape_((page), True), '&pagesize=', escape_((pagination.pagesize), True), '">\n')
                        if page == pagination.page:
                            yield '', join_('                                    ', '|', escape_((page), True), '|    \n')
                        else:
                            yield '', join_('                                    ', escape_(page, True), ' \n')
                        yield '', join_('                                ', '</a>\n')
                    else:
                        yield '', join_('                                ', escape_(pagination.separator, True), '\n')
                if pagination.has_more_entries():
                    yield '', join_('                                ', '       <a href="/topvoted?service=', escape_((service), True), '&tagged=', escape_((urlquote(tagged)), True), '&page=', escape_((pagination.page+1), True), '&pagesize=', escape_((pagination.pagesize), True), '">&nbsp;&nbsp;next &raquo;</a>\n')
                yield '', join_('                    ', '        </td>\n')
                yield '', join_('                    ', '        <td class="pagination_pagesize">Pagesize: ', escape_(pagination.pagesize, True), '</td>\n')
                yield '', join_('                    ', '    </tr>\n')
                yield '', join_('                    ', '</table>\n')
        else:
            if len(result) == 0:
                yield '', join_('                    ', '<p id="not_found">\n')
                yield '', join_('                    ', '    No questions found\n')
                yield '', join_('                    ', '</p>\n')
        yield '', join_('  </body>\n')
        yield '', join_('</html>\n')
    return __template__

topvoted_tagged = CompiledTemplate(topvoted_tagged(), 'app/views/topvoted_tagged.html')

